### ISSUE TITLE
Missing Argument in XenaManager.remove_port

### ISSUE THREAD

**Issue by akirabaruah** [AlgoLogic/XenaPythonLib#1]
Possibly missing the `module` argument [here](https://github.com/AlgoLogic/XenaPythonLib/blob/c2c7389fa2a62a1d3bee6a4c9c561e5498d80b50/xenalib/XenaManager.py#L73)

**Comment by akirabaruah** [comment]
@rayonix Do you agree that the missing argument is a bug?

**Comment by rayonix** [comment]
Ya that must be a bug
